import { Type } from '@sinclair/typebox';

// Schema for uploading a file
export const uploadFileSchema = {
  tags: ['files'],
  description: 'Upload a file to S3',
  security: [{ bearerAuth: [] }],
  body: Type.Object({
    fileName: Type.String({ description: 'Name of the file' }),
    fileType: Type.String({ description: 'MIME type of the file' }),
    fileSize: Type.Number({ description: 'Size of the file in bytes' }),
    filePath: Type.String({ 
      description: 'The S3 path/key where the file will be stored (generated by frontend)' 
    }),
    fileBuffer: Type.Optional(Type.String({ 
      description: 'Base64 encoded file content (optional, for direct upload)' 
    })),
    categoryId: Type.Optional(Type.Number({ 
      description: 'ID of the file category (optional, must belong to a library the user has access to)' 
    })),
  }),
  response: {
    201: Type.Object({
      id: Type.Number(),
      userId: Type.Number(),
      fileUrl: Type.String({ description: 'The S3 path/key of the uploaded file' }),
      fileName: Type.String(),
      fileType: Type.String(),
      fileSize: Type.Number(),
      categoryId: Type.Union([Type.Number(), Type.Null()], { description: 'ID of the file category, or null if uncategorized' }),
      downloadUrl: Type.String({ description: 'Presigned download URL (valid for 1 hour)' }),
      createdAt: Type.String(),
      updatedAt: Type.String(),
    }),
    400: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for getting a presigned upload URL
export const getUploadUrlSchema = {
  tags: ['files'],
  description: 'Get a presigned URL for uploading a file directly to S3',
  security: [{ bearerAuth: [] }],
  body: Type.Object({
    fileName: Type.String({ description: 'Name of the file' }),
    fileType: Type.String({ description: 'MIME type of the file' }),
    fileSize: Type.Number({ description: 'Size of the file in bytes' }),
    filePath: Type.String({ 
      description: 'The S3 path/key where the file will be stored (generated by frontend)' 
    }),
  }),
  response: {
    200: Type.Object({
      uploadUrl: Type.String({ description: 'Presigned URL for uploading' }),
      filePath: Type.String({ description: 'The S3 path/key for the file' }),
      expiresIn: Type.Number({ description: 'How long the URL is valid (in seconds)' }),
    }),
    400: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for confirming file upload
export const confirmUploadSchema = {
  tags: ['files'],
  description: 'Confirm that a file has been uploaded to S3 and create database record',
  security: [{ bearerAuth: [] }],
  body: Type.Object({
    fileName: Type.String(),
    fileType: Type.String(),
    fileSize: Type.Number(),
    filePath: Type.String(),
    categoryId: Type.Optional(Type.Number({ 
      description: 'ID of the file category (optional, must belong to a library the user has access to)' 
    })),
  }),
  response: {
    201: Type.Object({
      id: Type.Number(),
      userId: Type.Number(),
      fileUrl: Type.String(),
      fileName: Type.String(),
      fileType: Type.String(),
      fileSize: Type.Number(),
      categoryId: Type.Union([Type.Number(), Type.Null()], { description: 'ID of the file category, or null if uncategorized' }),
      downloadUrl: Type.String({ description: 'Presigned download URL (valid for 1 hour)' }),
      createdAt: Type.String(),
      updatedAt: Type.String(),
    }),
    400: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for getting a presigned download URL
export const getDownloadUrlSchema = {
  tags: ['files'],
  description: 'Get a presigned URL for downloading a file from S3',
  security: [{ bearerAuth: [] }],
  params: Type.Object({
    fileId: Type.Number({ description: 'ID of the file' }),
  }),
  response: {
    200: Type.Object({
      downloadUrl: Type.String({ description: 'Presigned URL for downloading' }),
      fileName: Type.String(),
      expiresIn: Type.Number({ description: 'How long the URL is valid (in seconds)' }),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    403: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    404: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for listing user files
export const listUserFilesSchema = {
  tags: ['files'],
  description: 'List all files for the authenticated user',
  security: [{ bearerAuth: [] }],
  querystring: Type.Object({
    limit: Type.Optional(Type.Number({ minimum: 1, maximum: 100, default: 50 })),
    offset: Type.Optional(Type.Number({ minimum: 0, default: 0 })),
  }),
  response: {
    200: Type.Object({
      files: Type.Array(
        Type.Object({
          id: Type.Number(),
          userId: Type.Number(),
          fileUrl: Type.String(),
          fileName: Type.String(),
          fileType: Type.String(),
          fileSize: Type.Number(),
          categoryId: Type.Union([Type.Number(), Type.Null()], { description: 'ID of the file category, or null if uncategorized' }),
          downloadUrl: Type.String({ description: 'Presigned download URL (valid for 1 hour)' }),
          createdAt: Type.String(),
          updatedAt: Type.String(),
        })
      ),
      total: Type.Number(),
      limit: Type.Number(),
      offset: Type.Number(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for listing uncategorized user files
export const listUncategorizedFilesSchema = {
  tags: ['files'],
  description: 'List all files for the authenticated user that are not in any category',
  security: [{ bearerAuth: [] }],
  querystring: Type.Object({
    limit: Type.Optional(Type.Number({ minimum: 1, maximum: 100, default: 50 })),
    offset: Type.Optional(Type.Number({ minimum: 0, default: 0 })),
  }),
  response: {
    200: Type.Object({
      files: Type.Array(
        Type.Object({
          id: Type.Number(),
          userId: Type.Number(),
          fileUrl: Type.String(),
          fileName: Type.String(),
          fileType: Type.String(),
          fileSize: Type.Number(),
          categoryId: Type.Null({ description: 'Always null for uncategorized files' }),
          downloadUrl: Type.String({ description: 'Presigned download URL (valid for 1 hour)' }),
          createdAt: Type.String(),
          updatedAt: Type.String(),
        })
      ),
      total: Type.Number(),
      limit: Type.Number(),
      offset: Type.Number(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for deleting a file
export const deleteFileSchema = {
  tags: ['files'],
  description: 'Delete a file from S3 and database',
  security: [{ bearerAuth: [] }],
  params: Type.Object({
    fileId: Type.Number({ description: 'ID of the file to delete' }),
  }),
  response: {
    200: Type.Object({
      message: Type.String(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    403: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    404: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for getting file details
export const getFileSchema = {
  tags: ['files'],
  description: 'Get details about a specific file',
  security: [{ bearerAuth: [] }],
  params: Type.Object({
    fileId: Type.Number({ description: 'ID of the file' }),
  }),
  response: {
    200: Type.Object({
      id: Type.Number(),
      userId: Type.Number(),
      fileUrl: Type.String(),
      fileName: Type.String(),
      fileType: Type.String(),
      fileSize: Type.Number(),
      categoryId: Type.Union([Type.Number(), Type.Null()], { description: 'ID of the file category, or null if uncategorized' }),
      downloadUrl: Type.String({ description: 'Presigned download URL (valid for 1 hour)' }),
      createdAt: Type.String(),
      updatedAt: Type.String(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    403: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    404: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

// Schema for updating a file
export const updateFileSchema = {
  tags: ['files'],
  description: 'Update file metadata (categoryId)',
  security: [{ bearerAuth: [] }],
  params: Type.Object({
    fileId: Type.Number({ description: 'ID of the file' }),
  }),
  body: Type.Object({
    categoryId: Type.Optional(Type.Union([Type.Number(), Type.Null()], { 
      description: 'ID of the file category, or null to remove from category. Must belong to a library the user has access to.' 
    })),
  }),
  response: {
    200: Type.Object({
      message: Type.String({ example: 'File updated successfully' }),
      file: Type.Object({
        id: Type.Number(),
        userId: Type.Number(),
        fileUrl: Type.String(),
        fileName: Type.String(),
        fileType: Type.String(),
        fileSize: Type.Number(),
        categoryId: Type.Union([Type.Number(), Type.Null()]),
        downloadUrl: Type.String({ description: 'Presigned download URL (valid for 1 hour)' }),
        createdAt: Type.String(),
        updatedAt: Type.String(),
      }),
    }),
    400: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    401: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    403: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
    404: Type.Object({
      error: Type.String(),
      message: Type.String(),
    }),
  },
};

